import type { Preview } from "@storybook/react";
import { withThemeByClassName } from "@storybook/addon-themes";

// Tailwind utilities (processed via PostCSS)
import "../src/tailwind.css";
// Import the built token CSS (generated by pnpm build-tokens)
import "@origin/tokens/css";

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    a11y: {
      // Enforce WCAG 2.1 AA across all stories
      config: {
        rules: [{ id: "color-contrast", enabled: true }],
      },
    },
    docs: {
      toc: true,
    },
  },
  decorators: [
    withThemeByClassName({
      themes: {
        light: "",
        dark: "dark",
      },
      defaultTheme: "light",
    }),
  ],
};

export default preview;
